### ISSUE TITLE
有研究吗？

### ISSUE THREAD

**Issue by liurongdev** [guanfuchen/video_obj#1]
老铁，你有研究这些论文以及代码吗？

**Comment by guanfuchen** [comment]
@liurongdev 研究过DFF系列和Seq-NMS的论文和代码，不过暂时没有自己完全实现代码，等到更加深入的理解以后会重写一下相关代码。

**Comment by liurongdev** [comment]
> @liurongdev 研究过DFF系列和Seq-NMS的论文和代码，不过暂时没有自己完全实现代码，等到更加深入的理解以后会重写一下相关代码。
老铁可以加个qq私聊下吗？1069919773

**Comment by liurongdev** [comment]
最近也在研究

**Comment by guanfuchen** [comment]
@liurongdev 设置了验证名字，没办法加你
